### ISSUE TITLE
how to config?

### ISSUE THREAD

**Issue by willin** [RobinMalfait/prepack-vscode#1]

**Comment by RobinMalfait** [comment]
Using all the config options ![](http://d.rbn.nu/qX1yf+)

**Comment by willin** [comment]
hi @RobinMalfait 

my source code are under `src` folder and i want to place the compiled code to `dist` folder.

when i use `prepack` cli tool :

```bash
 prepack .\src\doc.js
No sourcemap found at .\src\doc.js.map.
require is not defined
ReferenceError
    at .\src\doc.js:1:13
```

**Comment by RobinMalfait** [comment]
That's not an issue of the plugin, that is directly related to prepack. https://prepack.io
